{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tfautograph
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tfautograph_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tfautograph/tfautograph_{{ version }}.tar.gz
  sha256: 42821583679d32fa4abb4304b6831e8c3b4dce9468e1a3b570af7bf95ec0aa3a

build:
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-reticulate
    - r-backports
  run:
    - r-base
    - r-reticulate
    - r-backports
test:
  commands:
    - $R -e "library('tfautograph')"           # [not win]
    - "\"%R%\" -e \"library('tfautograph')\""  # [win]

about:
  home: https://t-kalinowski.github.io/tfautograph/
  license: GPL-3.0-only
  summary: Translate R control flow expressions into 'Tensorflow' graphs.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
